[package]
name = "mcp-planetscale"
version = "0.0.1"
edition = "2024"

[lib]
path = "src/mcp_planetscale.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
schemars = { version = "0.8", features = ["derive"] }
