id = "mcp-planetscale"
name = "PlanetScale MCP"
version = "0.0.1"
schema_version = 1
authors = ["Hunter Boyd <hunterjsb@gmail.com>"]
description = "Model Context Server for interatcting with databases on PlanetScale."
repository = "https://github.com/hunterjsb/zed-planetscale-mcp"

[slash_commands.hello]
description       = "Prints 'Hello, world!'"
requires_argument = false

[context_servers.mini-mcp]
name = "Mini MCP"
description = "Mini Model Context Protocol server with simple tools"
