id = "planetscale"
name = "PlanetScale"
version = "0.1.0"
schema_version = 1
authors = ["Hunter Satterwhite <hunter@satterwhite.dev>"]
description = "PlanetScale context server for Zed"
repository = "https://github.com/hunterjsb/zed-planetscale-mcp"

[context_servers.planetscale]