id = "zed-minimal-extension"
name = "Minimal Extension"
version = "0.1.0"
schema_version = 1
authors = ["Example User <user@example.com>"]
description = "A minimal example extension for Zed"
repository = "https://github.com/example/zed-minimal-extension"